### ISSUE TITLE
Downloading personalities 

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#160] opened 2020-09-24 23:05 UTC
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/patching/fixture-personalities/

**Old Text (if applicable):**
NA

**New Text:**
The personalities downloads are divided by the software version you are installing the update on, so be sure to check which version you are using by checking in either Tools- About or entering the system menu ( disk + Avo on consoles or the system button in TItanGo ) and seeing the version displayed in the prompt area .  

**Why it should be changed:**
There its a habit of users not downloading the correct version  and being confused when capture doesn't work correctly. but explaining it here is a good idea. 

**Other Information:**
Maybe add this also ( from the personalities page ) "The downloads contain the same Titan personalities which are compatible with all versions of Titan. The difference is which Capture library is included.

To install the fixture library, please copy the installer to a USB stick, plug it into the console then go to Tools > Control Panel > Titan Installers to run it. On PC, double click on the icon to install it."

but this might be all more info then the user needs in the manual

**Comment by congoblue** [comment] 2020-09-25 13:50
This fixture personalities section has been removed from the patching chapter as it was a duplicate of the reference section at the end of the manual, and I felt it was information that the basic user would not need.

I will add the info about versions to the reference chapter on personalities.

**Comment by congoblue** [comment] 2020-10-12 12:16
Fixed by #162

**Closed by congoblue** 2020-10-12 12:16 UTC
Labels: Correction
